/**
 * Company Entity Class
 * 
 * Represents customer/client companies (B2B healthcare organizations) in the MedSource Pro system.
 * Companies are organizations that place orders and request quotes for medical supplies.
 * 
 * **Key Business Flow Relationships:**
 * - PrimarySalesRepId: Dedicated sales rep for relationship continuity (CRITICAL)
 * - TypeOfBusiness: Segmentation for pricing, products, compliance
 * - Status: Customer lifecycle management (Active, Suspended, etc.)
 * 
 * **Features:**
 * - Company profile information (name, contact details)
 * - Business classification (typeOfBusiness)
 * - Account status tracking
 * - Primary sales rep assignment
 * - Multiple address support (general, shipping, billing)
 * - Tax identification
 * - Website reference
 * - Associated users/accounts
 * - Order history
 * - Quote history
 * - Timestamp tracking
 * 
 * **Related Entities:**
 * - User: Company employees/users
 * - Order: Company's order history
 * - Quote: Company's quote requests
 * - Address: Company addresses (main, shipping, billing)
 * - PrimarySalesRep: Assigned sales representative
 * 
 * @module Company
 */

import { parseRequiredTimestamp } from '@_lib/dates'

import { CustomerStatus, TypeOfBusiness } from '@_classes/Enums'
import Address from '@_classes/common/Address'
import Order from '@_classes/Order'
import Quote from '@_classes/Quote'
import User from '@_classes/User'


/**
 * Company Entity Class
 * 
 * Main company/customer entity representing B2B healthcare organizations.
 * Handles company profile, addresses, sales rep assignment, and relationships.
 */
export default class Company {
	/** Unique identifier (GUID, auto-generated by database) */
	id: string | null = null
	
	/** Company name */
	name: string = ''
	
	/** Primary contact email */
	email: string = ''
	
	/** Primary contact phone */
	phone: string = ''
	
	/** Tax identification number (EIN, VAT, etc.) */
	taxId: string = ''
	
	/** Company website URL */
	website: string = ''
	
	// =========================================================================
	// BUSINESS CLASSIFICATION (Critical for Business Flow)
	// =========================================================================
	
	/**
	 * Type of business for customer segmentation.
	 * Used for specialized pricing, product recommendations, compliance tracking.
	 */
	typeOfBusiness: TypeOfBusiness = TypeOfBusiness.Other
	
	/**
	 * Customer account status.
	 * Controls access to ordering capabilities.
	 */
	status: CustomerStatus = CustomerStatus.Active
	
	// =========================================================================
	// SALES REP ASSIGNMENT (Critical Business Differentiator)
	// =========================================================================
	
	/**
	 * Primary sales representative ID (GUID).
	 * Every customer gets a dedicated sales rep for relationship continuity.
	 * This is a KEY DIFFERENTIATOR vs competitors (McKesson, Amazon).
	 */
	primarySalesRepId: string | null = null
	
	/**
	 * Primary sales representative (populated when included in query).
	 */
	primarySalesRep: User | null = null
	
	/**
	 * Internal notes about the customer.
	 * Only visible to sales reps, sales managers, and admins.
	 * Not visible to customers.
	 */
	internalNotes: string = ''
	
	// =========================================================================
	// LEGACY FIELDS (Prefer structured addresses)
	// =========================================================================
	
	/** City (legacy field, prefer address object) */
	city: string = ''
	
	/** State/province (legacy field, prefer address object) */
	state: string = ''
	
	/** ZIP/postal code (legacy field, prefer address object) */
	zip: string = ''
	
	/** Country (legacy field, prefer address object) */
	country: string = ''
	
	/** Unique identifier for company (custom field) */
	identifier: string = ''
	
	// =========================================================================
	// ADDRESSES
	// =========================================================================
	
	/** Primary company address (structured Address entity) */
	address: Address = new Address()
	
	/** Shipping address (for deliveries) */
	shippingAddress: Address = new Address()
	
	/** Billing address (for invoices) */
	billingAddress: Address = new Address()
	
	// =========================================================================
	// TIMESTAMPS & FLAGS
	// =========================================================================
	
	/** Company creation timestamp */
	createdAt: Date = new Date()
	
	/** Last update timestamp */
	updatedAt: Date | null = null
	
	/** Soft delete flag */
	isArchived: boolean = false
	
	// =========================================================================
	// NAVIGATION PROPERTIES
	// =========================================================================

	/** Array of quote requests from this company */
	quotes: Quote[] = []
	
	/** Array of orders from this company */
	orders: Order[] = []
	
	/** Array of user accounts associated with this company */
	users: User[] = []

	/**
	 * Creates a new Company instance.
	 * Deeply copies nested objects (addresses, quotes, orders, users, primarySalesRep).
	 * Parses date strings to Date objects.
	 * Ensures identifier is never null (defaults to empty string).
	 * 
	 * @param {Partial<Company>} partial - Partial company data to initialize
	 */
	constructor(partial?: Partial<Company>) {
		if (partial) {
			Object.assign(this, partial)

			// Deep copy main address object
			if (partial.address) {
				this.address = new Address(partial.address)
			}
			
			// Deep copy shipping address
			if (partial.shippingAddress) {
				this.shippingAddress = new Address(partial.shippingAddress)
			}
			
			// Deep copy billing address
			if (partial.billingAddress) {
				this.billingAddress = new Address(partial.billingAddress)
			}
			
			// Deep copy primary sales rep if present
			if (partial.primarySalesRep) {
				this.primarySalesRep = new User(partial.primarySalesRep)
			}
			
			// Deep copy quotes array
			if (partial.quotes) {
				this.quotes = partial.quotes.map((q) => new Quote(q))
			}
			
			// Deep copy orders array
			if (partial.orders) {
				this.orders = partial.orders.map((o) => new Order(o))
			}
			
			// Deep copy users array
			if (partial.users) {
				this.users = partial.users.map((u) => new User(u))
			}

			// Ensure identifier is never null (use empty string as fallback)
			this.identifier = partial.identifier || ''
			
			// Ensure createdAt is always a Date object (required timestamp)
			this.createdAt = parseRequiredTimestamp(partial.createdAt, 'Company', 'createdAt')
		}
	}
	
	// =========================================================================
	// COMPUTED PROPERTIES
	// =========================================================================
	
	/**
	 * Get display-friendly business type name.
	 */
	get businessTypeName(): string {
		return TypeOfBusiness[this.typeOfBusiness] || 'Other'
	}
	
	/**
	 * Get display-friendly status name.
	 */
	get statusName(): string {
		return CustomerStatus[this.status] || 'Unknown'
	}
	
	/**
	 * Check if customer is active and can place orders.
	 */
	get isActive(): boolean {
		return this.status === CustomerStatus.Active && !this.isArchived
	}
	
	/**
	 * Get the primary sales rep's display name.
	 */
	get salesRepName(): string | null {
		if (!this.primarySalesRep) return null
		const name = this.primarySalesRep.name
		if (name?.first || name?.last) {
			return [name.first, name.last].filter(Boolean).join(' ')
		}
		return this.primarySalesRep.username || null
	}
}
