/**
 * Company Entity Class
 * 
 * Represents customer/client companies in the MedSource Pro system.
 * Companies are organizations that place orders and request quotes for medical supplies.
 * Each company can have multiple users, orders, and quotes associated with it.
 * 
 * **Features:**
 * - Company profile information (name, contact details)
 * - Multiple address support (general, shipping, billing)
 * - Tax identification
 * - Website reference
 * - Associated users/accounts
 * - Order history
 * - Quote history
 * - Timestamp tracking
 * 
 * **Related Entities:**
 * - User: Company employees/users
 * - Order: Company's order history
 * - Quote: Company's quote requests
 * - Address: Company addresses (main, shipping, billing)
 * 
 * @example
 * ```typescript
 * // Create a new company
 * const company = new Company({
 *   name: 'Springfield Medical Center',
 *   email: 'orders@springfieldmed.com',
 *   phone: '555-123-4567',
 *   city: 'Springfield',
 *   state: 'IL',
 *   zip: '62701',
 *   country: 'USA',
 *   taxId: '12-3456789',
 *   website: 'https://springfieldmed.com',
 *   address: new Address({
 *     addressOne: '123 Medical Plaza',
 *     city: 'Springfield',
 *     state: 'IL',
 *     zipCode: '62701',
 *     country: 'USA'
 *   })
 * });
 * 
 * // Company with users and orders
 * const company2 = new Company({
 *   name: 'Metro Hospital',
 *   users: [
 *     new User({ username: 'john.doe', email: 'john@metro.com' }),
 *     new User({ username: 'jane.smith', email: 'jane@metro.com' })
 *   ],
 *   orders: [
 *     new Order({ id: 1, total: 1500.00 }),
 *     new Order({ id: 2, total: 2200.00 })
 *   ]
 * });
 * ```
 * 
 * @module Company
 */

import Quote from '@_classes/Quote'
import User from '@_classes/User'
import Order from '@_classes/Order'
import Address from '@_classes/common/Address'
import { parseRequiredTimestamp } from '@_lib/dates'

/**
 * Company Entity Class
 * 
 * Main company/customer entity representing organizations that purchase medical supplies.
 * Handles company profile, addresses, relationships to users and orders.
 */
export default class Company {
	/** Unique identifier (auto-generated by database) */
	id: number = 0
	
	/** Company name */
	name: string = ''
	
	/** Primary contact email */
	email: string = ''
	
	/** Primary contact phone */
	phone: string = ''
	
	/** City (legacy field, prefer address object) */
	city: string = ''
	
	/** State/province (legacy field, prefer address object) */
	state: string = ''
	
	/** ZIP/postal code (legacy field, prefer address object) */
	zip: string = ''
	
	/** Country (legacy field, prefer address object) */
	country: string = ''
	
	/** Unique identifier for company (custom field) */
	identifier: string = ''
	
	/** Tax identification number (EIN, VAT, etc.) */
	taxId: string = ''  // Added for tax identification
	
	/** Company website URL */
	website: string = ''  // Added for company website
	
	/** Primary company address (structured Address entity) */
	address: Address = new Address()  // Added for simplified address reference
	
	/** Company creation timestamp */
	createdAt: Date = new Date()
	
	/** Last update timestamp */
	updatedAt: Date | null = null
	
	/** Shipping address (for deliveries) */
	shippingAddress: Address = new Address()
	
	/** Billing address (for invoices) */
	billingAddress: Address = new Address()

	/** Array of quote requests from this company */
	quotes: Quote[] = []
	
	/** Array of orders from this company */
	orders: Order[] = []
	
	/** Array of user accounts associated with this company */
	users: User[] = []

	/**
	 * Creates a new Company instance.
	 * Deeply copies nested objects (addresses, quotes, orders, users).
	 * Parses date strings to Date objects.
	 * Ensures identifier is never null (defaults to empty string).
	 * 
	 * @param {Partial<Company>} partial - Partial company data to initialize
	 * 
	 * @example
	 * ```typescript
	 * // Basic company
	 * const company = new Company({
	 *   name: 'City Hospital',
	 *   email: 'admin@cityhospital.com',
	 *   phone: '555-987-6543',
	 *   city: 'Chicago',
	 *   state: 'IL',
	 *   country: 'USA'
	 * });
	 * 
	 * // Company with full address details
	 * const company2 = new Company({
	 *   name: 'Regional Medical',
	 *   taxId: '98-7654321',
	 *   website: 'https://regionalmed.com',
	 *   shippingAddress: new Address({
	 *     addressOne: '456 Health St',
	 *     city: 'Boston',
	 *     state: 'MA',
	 *     zipCode: '02101',
	 *     country: 'USA'
	 *   }),
	 *   billingAddress: new Address({
	 *     addressOne: 'PO Box 789',
	 *     city: 'Boston',
	 *     state: 'MA',
	 *     zipCode: '02102',
	 *     country: 'USA'
	 *   })
	 * });
	 * ```
	 */
	constructor(partial?: Partial<Company>) {
		if (partial) {
			Object.assign(this, partial) // Assign provided properties

			// Deep copy main address object
			if (partial.address) {
				this.address = new Address(partial.address)
			}
			
			// Deep copy shipping address
			if (partial.shippingAddress) {
				this.shippingAddress = new Address(partial.shippingAddress)
			}
			
			// Deep copy billing address
			if (partial.billingAddress) {
				this.billingAddress = new Address(partial.billingAddress)
			}
			
			// Deep copy quotes array
			if (partial.quotes) {
				this.quotes = partial.quotes.map((q) => new Quote(q))
			}
			
			// Deep copy orders array
			if (partial.orders) {
				this.orders = partial.orders.map((o) => new Order(o))
			}
			
			// Deep copy users array
			if (partial.users) {
				this.users = partial.users.map((u) => new User(u))
			}

			// Ensure identifier is never null (use empty string as fallback)
			this.identifier = partial.identifier || ''
			
			// Ensure createdAt is always a Date object (required timestamp)
			this.createdAt = parseRequiredTimestamp(partial.createdAt, 'Company', 'createdAt')
		}
	}
}
