/**
 * Product Category Entity Class
 * 
 * Represents hierarchical product categories in the MedSource Pro catalog system.
 * Supports nested category structures with parent-child relationships.
 * Categories organize products into logical groups for easier browsing and filtering.
 * 
 * **Features:**
 * - Hierarchical category structure (parent/sub-categories)
 * - Parent-child relationships
 * - Nested sub-categories
 * - Category sanitization utility function
 * 
 * **Category Structure:**
 * - Root categories have no parentCategoryId (null or undefined)
 * - Sub-categories have parentCategoryId pointing to parent
 * - Categories can have multiple sub-categories
 * - Circular references are prevented
 * 
 * **Related Entities:**
 * - Product: Products belong to categories
 * 
 * @example
 * ```typescript
 * // Create a root category
 * const medicalSupplies = new ProductsCategory({
 *   id: 1,
 *   name: 'Medical Supplies'
 * });
 * 
 * // Create sub-categories
 * const ppe = new ProductsCategory({
 *   id: 2,
 *   name: 'Personal Protective Equipment',
 *   parentCategoryId: 1,
 *   parentCategory: medicalSupplies
 * });
 * 
 * const masks = new ProductsCategory({
 *   id: 3,
 *   name: 'Masks',
 *   parentCategoryId: 2,
 *   parentCategory: ppe
 * });
 * 
 * // Add sub-categories to parent
 * medicalSupplies.subCategories.push(ppe);
 * ppe.subCategories.push(masks);
 * 
 * // Sanitize flat category list from backend
 * const flatCategories = [
 *   { id: 1, name: 'Medical Supplies', parentCategoryId: null },
 *   { id: 2, name: 'PPE', parentCategoryId: 1 },
 *   { id: 3, name: 'Masks', parentCategoryId: 2 },
 *   { id: 4, name: 'Surgical Equipment', parentCategoryId: 1 }
 * ];
 * const hierarchical = sanitizeCategoriesList(flatCategories);
 * // Returns [Medical Supplies (with PPE and Surgical Equipment as sub-categories)]
 * ```
 * 
 * @module ProductsCategory
 */

/**
 * ProductsCategory Entity Class
 * 
 * Main product category entity representing a category in the product catalog.
 * Supports hierarchical structure with parent-child relationships.
 */
export default class ProductsCategory {
	/** Unique identifier (auto-generated by database) */
	id: number = -99
	
	/** Category name (e.g., "Medical Supplies", "PPE", "Masks") */
	name?: string
	
	/** Parent category ID (null for root categories) */
	parentCategoryId?: number
	
	/** Reference to parent category object (for navigation) */
	parentCategory?: ProductsCategory | null
	
	/** Array of child categories (sub-categories) */
	subCategories: ProductsCategory[] = []

	/**
	 * Creates a new ProductsCategory instance.
	 * Performs shallow copy of properties.
	 * 
	 * @param {Partial<ProductsCategory>} partial - Partial category data to initialize
	 * 
	 * @example
	 * ```typescript
	 * // Root category
	 * const rootCategory = new ProductsCategory({
	 *   id: 1,
	 *   name: 'Medical Supplies'
	 * });
	 * 
	 * // Sub-category
	 * const subCategory = new ProductsCategory({
	 *   id: 2,
	 *   name: 'PPE',
	 *   parentCategoryId: 1
	 * });
	 * 
	 * // Link sub-category to parent
	 * subCategory.parentCategory = rootCategory;
	 * rootCategory.subCategories.push(subCategory);
	 * ```
	 */
	constructor(partial?: Partial<ProductsCategory>) {
		if (partial) {Object.assign(this, partial)}
	}
}

/**
 * Sanitizes a flat list of categories into a hierarchical structure.
 * 
 * Converts a flat array of categories from the backend into a hierarchical tree
 * by establishing parent-child relationships and filtering out sub-categories from
 * the root level. This is commonly used after fetching all categories from the API.
 * 
 * **Algorithm:**
 * 1. Creates a map of all categories by ID for quick lookup
 * 2. Iterates through categories and links children to parents
 * 3. Populates subCategories arrays on parent categories
 * 4. Filters result to return only root-level categories
 * 
 * **Performance:**
 * - Time complexity: O(n) where n is the number of categories
 * - Space complexity: O(n) for the category map
 * 
 * @param {ProductsCategory[]} categories - Flat array of categories from backend
 * @returns {ProductsCategory[]} Array of root-level categories with nested sub-categories
 * 
 * @example
 * ```typescript
 * // Backend returns flat list
 * const flatCategories: ProductsCategory[] = [
 *   { id: 1, name: 'Medical Supplies', parentCategoryId: null },
 *   { id: 2, name: 'PPE', parentCategoryId: 1 },
 *   { id: 3, name: 'Masks', parentCategoryId: 2 },
 *   { id: 4, name: 'Gloves', parentCategoryId: 2 },
 *   { id: 5, name: 'Surgical Equipment', parentCategoryId: 1 },
 *   { id: 6, name: 'Scalpels', parentCategoryId: 5 }
 * ];
 * 
 * // Sanitize to hierarchical structure
 * const hierarchical = sanitizeCategoriesList(flatCategories);
 * 
 * // Result:
 * // [
 * //   {
 * //     id: 1,
 * //     name: 'Medical Supplies',
 * //     subCategories: [
 * //       {
 * //         id: 2,
 * //         name: 'PPE',
 * //         parentCategoryId: 1,
 * //         subCategories: [
 * //           { id: 3, name: 'Masks', parentCategoryId: 2, subCategories: [] },
 * //           { id: 4, name: 'Gloves', parentCategoryId: 2, subCategories: [] }
 * //         ]
 * //       },
 * //       {
 * //         id: 5,
 * //         name: 'Surgical Equipment',
 * //         parentCategoryId: 1,
 * //         subCategories: [
 * //           { id: 6, name: 'Scalpels', parentCategoryId: 5, subCategories: [] }
 * //         ]
 * //       }
 * //     ]
 * //   }
 * // ]
 * 
 * // Use in category selector
 * const renderCategory = (category: ProductsCategory, depth: number = 0) => {
 *   return (
 *     <div style={{ marginLeft: depth * 20 }}>
 *       <option value={category.id}>{category.name}</option>
 *       {category.subCategories.map(sub => renderCategory(sub, depth + 1))}
 *     </div>
 *   );
 * };
 * ```
 */
export function sanitizeCategoriesList(categories: ProductsCategory[]): ProductsCategory[] {
	// Create a map for O(1) lookup of categories by ID
	const categoriesMap = new Map<number, ProductsCategory>()

	// First pass: Map all categories by their ID
	categories.forEach((category) => {
		categoriesMap.set(category.id, category)
	})

	// Second pass: Establish parent-child relationships
	categories.forEach((category) => {
		// If category has a parent ID, link it to the parent
		if (category.parentCategoryId !== null && category.parentCategoryId !== undefined) {
			const parentCategory = categoriesMap.get(category.parentCategoryId)
			if (parentCategory) {
				// Add this category to parent's sub-categories array
				parentCategory.subCategories.push(category)
				// Set parent reference on child
				category.parentCategory = parentCategory
			}
		}
	})

	// Third pass: Filter to return only root-level categories
	// Root categories have no parent (parentCategoryId is null or undefined)
	const sanitizedCategories: ProductsCategory[] = []
	categories.forEach((category) => {
		if (category.parentCategoryId === null || category.parentCategoryId === undefined) {
			sanitizedCategories.push(category)
		}
	})

	return sanitizedCategories
}
