/**
 * Provider Entity Class
 * 
 * Represents medical supply providers/suppliers in the MedSource Pro system.
 * Providers are companies that supply products to MedSource for resale.
 * Similar structure to Company but represents the supplier side of the business.
 * 
 * **Features:**
 * - Provider profile information (name, contact details)
 * - Address management (structured and legacy fields)
 * - Tax identification
 * - Website reference
 * - Product catalog (products supplied by this provider)
 * - Status workflow (Active -> Suspended -> Archived)
 * - Timestamp tracking
 * 
 * **Status Workflow (Industry Best Practice):**
 * - Active: Provider is available for orders
 * - Suspended: Temporary hold (compliance, performance issues)
 * - Archived: Permanently deactivated
 * 
 * **Related Entities:**
 * - Product: Products supplied by this provider
 * - Address: Provider's business address
 * 
 * @example
 * ```typescript
 * // Create a new provider
 * const provider = new Provider({
 *   name: 'Medical Supplies Inc.',
 *   email: 'sales@medicalsupplies.com',
 *   phone: '555-123-4567',
 *   taxId: '12-3456789',
 *   website: 'https://medicalsupplies.com',
 *   identifier: 'MSI-001',
 *   status: ProviderStatus.Active,
 *   address: new Address({
 *     addressOne: '789 Industrial Blvd',
 *     city: 'Chicago',
 *     state: 'IL',
 *     zipCode: '60601',
 *     country: 'USA'
 *   }),
 * });
 * ```
 * 
 * @module Provider
 */

import { parseDateSafe, parseRequiredTimestamp } from '@_lib/dates'

import Address from '@_classes/common/Address'
import { ProviderStatus } from '@_classes/Enums'

import { Product } from './Product'

// Re-export for convenience
export { ProviderStatus }

/**
 * Provider Entity Class
 * 
 * Main provider/supplier entity representing companies that supply medical products.
 * Handles provider profile, address, contact information, and product catalog.
 */
export default class Provider {
	/** Unique identifier (auto-generated by database) */
	id: number = 0
	
	/** Provider/company name */
	name: string = ''
	
	/** Primary contact email */
	email: string = ''
	
	/** Primary contact phone */
	phone: string = ''
	
	/** Tax identification number (EIN, VAT, etc.) */
	taxId: string = ''
	
	/** Provider website URL */
	website: string = ''
	
	/** Unique provider identifier (custom field for tracking) */
	identifier: string = ''
	
	/** Structured address object (preferred for new implementations) */
	address: Address = new Address()
	
	// Legacy flat address fields for backward compatibility
	/** City (legacy field, prefer address object) */
	city: string = ''
	
	/** State/province (legacy field, prefer address object) */
	state: string = ''
	
	/** ZIP/postal code (legacy field, prefer address object) */
	zip: string = ''
	
	/** Country (legacy field, prefer address object) */
	country: string = ''
	
	/** Array of products supplied by this provider */
	products: Product[] = []
	
	/** Provider record creation timestamp */
	createdAt: Date = new Date()
	
	/** Last update timestamp */
	updatedAt: Date | null = null

	/**
	 * Provider status (Active, Suspended, Archived).
	 * Follows industry best practices for vendor lifecycle management.
	 */
	status: ProviderStatus = ProviderStatus.Active

	/** Reason for suspension (if status === Suspended) */
	suspensionReason: string = ''

	/** Date when status was last changed */
	statusChangedAt: Date | null = null

	/** Internal notes about this provider */
	notes: string = ''

	/**
	 * Legacy isArchived property for backward compatibility.
	 * Maps to status === Archived.
	 */
	get isArchived(): boolean {
		return this.status === ProviderStatus.Archived
	}

	set isArchived(value: boolean) {
		this.status = value ? ProviderStatus.Archived : ProviderStatus.Active
	}

	/**
	 * Check if provider is suspended.
	 */
	get isSuspended(): boolean {
		return this.status === ProviderStatus.Suspended
	}

	/**
	 * Check if provider is active (not suspended or archived).
	 */
	get isActive(): boolean {
		return this.status === ProviderStatus.Active
	}

	/**
	 * Creates a new Provider instance.
	 * Deeply copies nested objects (address, products).
	 * Parses date strings to Date objects.
	 * 
	 * @param {Partial<Provider>} partial - Partial provider data to initialize
	 * 
	 * @example
	 * ```typescript
	 * // Basic provider
	 * const provider = new Provider({
	 *   name: 'Global Medical Supplies',
	 *   email: 'contact@globalmedicalsupplies.com',
	 *   phone: '555-111-2222',
	 *   taxId: '98-7654321',
	 *   identifier: 'GMS-100'
	 * });
	 * 
	 * // Provider with full address and products
	 * const provider2 = new Provider({
	 *   name: 'Premier Healthcare Distributors',
	 *   email: 'sales@premierhc.com',
	 *   phone: '555-333-4444',
	 *   taxId: '11-2233445',
	 *   website: 'https://premierhc.com',
	 *   identifier: 'PHD-200',
	 *   address: new Address({
	 *     addressOne: '123 Distribution Center Dr',
	 *     city: 'Dallas',
	 *     state: 'TX',
	 *     zipCode: '75201',
	 *     country: 'USA'
	 *   }),
	 *   products: [
	 *     new Product({ name: 'PPE Kit', providerId: 2 }),
	 *     new Product({ name: 'Exam Gloves', providerId: 2 })
	 *   ]
	 * });
	 * ```
	 */
	constructor(partial?: Partial<Provider> & { isArchived?: boolean }) {
		if (partial) {
			// Don't assign isArchived directly since it's a getter/setter
			const { isArchived: _isArchived, ...rest } = partial
			Object.assign(this, rest)
			
			// Deep copy address object
			if (partial.address) {
				this.address = new Address(partial.address)
			}
			
			// Parse creation date from string if needed (required timestamp - always validate)
			this.createdAt = parseRequiredTimestamp(partial.createdAt, 'Provider', 'createdAt')
			
			// Parse update date from string if needed (optional - null until updated)
			if (partial.updatedAt !== undefined) {
				this.updatedAt = parseDateSafe(partial.updatedAt)
			}

			// Parse status changed date if provided
			if (partial.statusChangedAt !== undefined) {
				this.statusChangedAt = parseDateSafe(partial.statusChangedAt)
			}
			
			// Handle status (new enum-based system)
			if (partial.status !== undefined) {
				this.status = partial.status
			}
			// Handle legacy isArchived for backward compatibility
			else if (_isArchived !== undefined) {
				this.status = _isArchived ? ProviderStatus.Archived : ProviderStatus.Active
			}
			
			// Deep copy products array
			if (this.products) {this.products = this.products.map((p) => new Product(p))}
		}
	}
}
