/**
 * Provider Entity Class
 * 
 * Represents medical supply providers/suppliers in the MedSource Pro system.
 * Providers are companies that supply products to MedSource for resale.
 * Similar structure to Company but represents the supplier side of the business.
 * 
 * **Features:**
 * - Provider profile information (name, contact details)
 * - Address management (structured and legacy fields)
 * - Tax identification
 * - Website reference
 * - Product catalog (products supplied by this provider)
 * - Timestamp tracking
 * 
 * **Related Entities:**
 * - Product: Products supplied by this provider
 * - Address: Provider's business address
 * 
 * @example
 * ```typescript
 * // Create a new provider
 * const provider = new Provider({
 *   name: 'Medical Supplies Inc.',
 *   email: 'sales@medicalsupplies.com',
 *   phone: '555-123-4567',
 *   taxId: '12-3456789',
 *   website: 'https://medicalsupplies.com',
 *   identifier: 'MSI-001',
 *   address: new Address({
 *     addressOne: '789 Industrial Blvd',
 *     city: 'Chicago',
 *     state: 'IL',
 *     zipCode: '60601',
 *     country: 'USA'
 *   }),
 *   products: [
 *     new Product({ name: 'Surgical Mask', providerId: 1 }),
 *     new Product({ name: 'N95 Respirator', providerId: 1 })
 *   ]
 * });
 * 
 * // Provider with legacy address fields
 * const provider2 = new Provider({
 *   name: 'Healthcare Distributors',
 *   email: 'orders@hcdist.com',
 *   phone: '555-987-6543',
 *   city: 'New York',
 *   state: 'NY',
 *   zip: '10001',
 *   country: 'USA'
 * });
 * ```
 * 
 * @module Provider
 */

import { Product } from './Product'
import Address from '@_classes/common/Address'
import { parseDateSafe } from '@_lib/dates'

/**
 * Provider Entity Class
 * 
 * Main provider/supplier entity representing companies that supply medical products.
 * Handles provider profile, address, contact information, and product catalog.
 */
export default class Provider {
	/** Unique identifier (auto-generated by database) */
	id: number = 0
	
	/** Provider/company name */
	name: string = ''
	
	/** Primary contact email */
	email: string = ''
	
	/** Primary contact phone */
	phone: string = ''
	
	/** Tax identification number (EIN, VAT, etc.) */
	taxId: string = ''
	
	/** Provider website URL */
	website: string = ''
	
	/** Unique provider identifier (custom field for tracking) */
	identifier: string = ''
	
	/** Structured address object (preferred for new implementations) */
	address: Address = new Address()
	
	// Legacy flat address fields for backward compatibility
	/** City (legacy field, prefer address object) */
	city: string = ''
	
	/** State/province (legacy field, prefer address object) */
	state: string = ''
	
	/** ZIP/postal code (legacy field, prefer address object) */
	zip: string = ''
	
	/** Country (legacy field, prefer address object) */
	country: string = ''
	
	/** Array of products supplied by this provider */
	products: Product[] = []
	
	/** Provider record creation timestamp */
	createdAt: Date = new Date()
	
	/** Last update timestamp */
	updatedAt: Date | null = null

	/**
	 * Creates a new Provider instance.
	 * Deeply copies nested objects (address, products).
	 * Parses date strings to Date objects.
	 * 
	 * @param {Partial<Provider>} partial - Partial provider data to initialize
	 * 
	 * @example
	 * ```typescript
	 * // Basic provider
	 * const provider = new Provider({
	 *   name: 'Global Medical Supplies',
	 *   email: 'contact@globalmedicalsupplies.com',
	 *   phone: '555-111-2222',
	 *   taxId: '98-7654321',
	 *   identifier: 'GMS-100'
	 * });
	 * 
	 * // Provider with full address and products
	 * const provider2 = new Provider({
	 *   name: 'Premier Healthcare Distributors',
	 *   email: 'sales@premierhc.com',
	 *   phone: '555-333-4444',
	 *   taxId: '11-2233445',
	 *   website: 'https://premierhc.com',
	 *   identifier: 'PHD-200',
	 *   address: new Address({
	 *     addressOne: '123 Distribution Center Dr',
	 *     city: 'Dallas',
	 *     state: 'TX',
	 *     zipCode: '75201',
	 *     country: 'USA'
	 *   }),
	 *   products: [
	 *     new Product({ name: 'PPE Kit', providerId: 2 }),
	 *     new Product({ name: 'Exam Gloves', providerId: 2 })
	 *   ]
	 * });
	 * ```
	 */
	constructor(partial?: Partial<Provider>) {
		if (partial) {
			Object.assign(this, partial)
			
			// Deep copy address object
			if (partial.address) {
				this.address = new Address(partial.address)
			}
			
			// Parse creation date from string if needed
			if (partial.createdAt) this.createdAt = parseDateSafe(partial.createdAt) ?? new Date()
			
			// Parse update date from string if needed
			if (partial.updatedAt) this.updatedAt = parseDateSafe(partial.updatedAt) ?? new Date()
			
			// Deep copy products array
			if (this.products) this.products = this.products.map((p) => new Product(p))
		}
	}
}
