import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import NavBar from '@/components/NavBar'
import WrapperHandlerPublic from '@/components/WrapperHandlerPublic'
import Breadcrumb from '@/src/components/Navigation/BreadCrumb'

import '@fortawesome/fontawesome-free/css/all.min.css'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'
import '@/styles/navigations.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout(props: any) {
	return (
		<html lang='en'>
			<body>
				<WrapperHandlerPublic />
				<NavBar />

				<main className='page-container'>
					<Breadcrumb />
					{props.children}
				</main>
				<ToastContainer />
			</body>
		</html>
	)
}
