import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
	title: 'The best app ever. Trust me. I know. I made it. I Aint No Lie',
	description: 'Generated by two prodigies.',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const cookiesStore = cookies()
	const token = cookiesStore.get('at')

	// Load user data into state management library.

	if (token == null) redirect('/login')

	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	)
}
